### ISSUE TITLE
problem with python v 3.13 (?)

### ISSUE THREAD

**Issue by philbat** [sanderland/katrain#732]
Please read and fill in the appropriate template

# I have a question about using the program, or need technical assistance

Please use the Computer Go Community Discord (#gui) : http://discord.gg/AjTPFpN

# I have a bug report

Please include details of the settings you use, steps to reproduce the problem, and console output.
on debian trixie up to date and python 3.13
compiling katago ok
pipx install katrain ok
when i launch the program, it is ok,  but when i click to put a stone, i get the following message , "python (v 3.13) ne répond pas" in french. 

![Image](https://github.com/user-attachments/assets/fd0022b9-c300-467a-a519-5373acc2e902)

# I have a feature request

Go ahead, but keep in mind that the program is mostly in maintenance mode, and big changes are unlikely.

**Comment by philbat** [comment]
I mean : is this an issue with katrain or with python (standard installation on debian) ?

**Comment by philbat** [comment]
I have read issue #726, so I 
git clone https://github.com/sanderland/katrain.git,
then I have modified pyproject.toml with
kivy = {extras = ["full"], version = "=2.3.0"}
then
pipx install .

but 
pip failed to build package:
    kivy

**Comment by lane-westlund** [comment]
I get the same error (python not responding) due to kivy:

WARNING] [MTD         ] Unable to open device "/dev/input/event6". Please ensure you have the appropriate permissions.

**Comment by kingjuno** [comment]
same error. I tried on 3.9 and still getting same error. @sanderland can you please look into this if possible.

**Comment by TristanCacqueray** [comment]
Thanks @lane-westlund , I had the same issue, and downgrading kivy worked, though it doesn't seem to build with py3.13, so I also had to downgrade to py3.12.

For the record, the build failure was:

```
      /tmp/pip-install-txdm5e5t/kivy_ca5155994c5347e29515df38bc2ab98b/kivy/graphics/svg.c: In function ‘__Pyx_PyGen_Send’:
      /tmp/pip-install-txdm5e5t/kivy_ca5155994c5347e29515df38bc2ab98b/kivy/graphics/svg.c:59467:13: error: implicit declaration of function ‘_PyGen_SetStopIterationValue’; did you mean ‘__Pyx_PyGen__FetchStopIterationValue’? [-Wimplicit-function-declaration]
      59467 |             _PyGen_SetStopIterationValue(result);
            |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |             __Pyx_PyGen__FetchStopIterationValue
       error: command '/usr/bin/gcc' failed with exit code 1
```
